### ISSUE TITLE
没有成功显示字幕

### ISSUE THREAD

**Issue by BenPong** [rerender2021/echo#17]
在系统设置中设置输入的立体声的时候，windows11设置与windows10是不一样的，所以不知道怎么在windows11中设置？
所以我安装使用Voicemeeter；但是字幕并没有成功的显示出来。不知道是Voicemeeter不能代替在设置输入立体声还是其他问题

**Comment by rerender2021** [comment]
win11：可以试试搜搜解答：
- https://answers.microsoft.com/zh-hans/windows/forum/all/win11%E6%B2%A1%E6%9C%89%E7%AB%8B%E4%BD%93%E5%A3%B0/255778cb-dde4-43d8-97dc-98891545bb24
- https://www.ylmfwin100.net/ylmf/8942.html

---

Voicemeeter：我没有使用过这个进行测试

**Comment by BenPong** [comment]
我在主板的官网找到声卡驱动realtek audio，安装之后已经成功的在win11的声音输入设置：立体声混音，但是字幕还是没有成功显示，不知道为什么？以下和附件我附上使用echo-v1.1.0-debug.exe得到的报错信息，请帮我看一下问题出在哪里？谢谢。




###
parse config succeed, use it
parse config succeed, use it
try to init vosk asr engine
use asr-server-v1.1.0
asrDir exists, start asr server C:\Users\BenSa\Downloads\echo-v1.1.0.exe\echo\asr-server-v1.1.0
try to init nlp engine
use nlp-server
nlpDir exists, start nlp server C:\Users\BenSa\Downloads\echo-v1.1.0.exe\echo\nlp-server
stdout: 2023-05-10 21:28:25.974  INFO : NLP API is starting, please wait...


stdout: 2023-05-10 21:28:25.974  INFO : NLP-API model dir: C:\Users\BenSa\Downloads\echo-v1.1.0.exe\echo\nlp-server\model


stdout: 2023-05-10 21:28:27.055  INFO : ASR API is starting, please wait...


stdout: torch info:
2.0.0+cpu
None
False


stdout: 2023-05-10 21:28:30.086  INFO : NLP API has been started
      Endpoint: POST http://127.0.0.1:8100/translate
      Language: en to zh


nlp server started
(node:6776) UnhandledPromiseRejectionWarning: AxiosError: Request failed with status code 404
    at settle (C:\snapshot\dist\_\_\app.js)
    at IncomingMessage.handleStreamEnd (C:\snapshot\dist\_\_\app.js)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `echo-v1.1.0-debug --trace-warnings ...` to show where the warning was created)
(node:6776) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:6776) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
stderr: transformers\pipelines\token_classification.py:157: UserWarning: `grouped_entities` is deprecated and will be removed in version v5.0.0, defaulted to `aggregation_strategy="none"` instead.
  warnings.warn(


stdout: 2023-05-10 21:28:32.484
stdout: advance model exists:  False
 INFO : init end
model path: C:\Users\BenSa\Downloads\echo-v1.1.0.exe\echo\asr-server-v1.1.0\./model/vosk-model-en-us-0.22-lgraph


stderr:  INFO:ASR-API:init end


stdout: 2023-05-10 21:28:32.529  INFO : ASR API has been started
      Endpoint: POST http://127.0.0.1:8200/asr


asr server started
stderr:  INFO:ASR-API:ASR API has been started
  Endpoint: POST http://127.0.0.1:8200/asr


stderr: INFO:root:will run asr client


stderr: INFO:websockets.server:server listening on 0.0.0.0:8210


stderr: INFO:websockets.server:connection open


stderr: INFO:root:Connection from ('127.0.0.1', 60621)


stderr: INFO:root:Config {'sample_rate': 16000}
###





在 2023-05-11 08:53:32，"rerender2021" ***@***.***> 写道：

win11：可以试试搜搜解答：

https://answers.microsoft.com/zh-hans/windows/forum/all/win11%E6%B2%A1%E6%9C%89%E7%AB%8B%E4%BD%93%E5%A3%B0/255778cb-dde4-43d8-97dc-98891545bb24
https://www.ylmfwin100.net/ylmf/8942.html

Voicemeeter：我没有使用过这个进行测试

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
parse config succeed, use it
parse config succeed, use it
try to init vosk asr engine
use asr-server-v1.1.0
asrDir exists, start asr server C:\Users\BenSa\Downloads\echo-v1.1.0.exe\echo\asr-server-v1.1.0
try to init nlp engine
use nlp-server
nlpDir exists, start nlp server C:\Users\BenSa\Downloads\echo-v1.1.0.exe\echo\nlp-server
stdout: 2023-05-10 21:28:25.974  INFO : NLP API is starting, please wait...

stdout: 2023-05-10 21:28:25.974  INFO : NLP-API model dir: C:\Users\BenSa\Downloads\echo-v1.1.0.exe\echo\nlp-server\model

stdout: 2023-05-10 21:28:27.055  INFO : ASR API is starting, please wait...

stdout: torch info:
2.0.0+cpu
None
False

stdout: 2023-05-10 21:28:30.086  INFO : NLP API has been started
      Endpoint: POST http://127.0.0.1:8100/translate
      Language: en to zh

nlp server started
(node:6776) UnhandledPromiseRejectionWarning: AxiosError: Request failed with status code 404
    at settle (C:\snapshot\dist\_\_\app.js)
    at IncomingMessage.handleStreamEnd (C:\snapshot\dist\_\_\app.js)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `echo-v1.1.0-debug --trace-warnings ...` to show where the warning was created)
(node:6776) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:6776) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
stderr: transformers\pipelines\token_classification.py:157: UserWarning: `grouped_entities` is deprecated and will be removed in version v5.0.0, defaulted to `aggregation_strategy="none"` instead.
  warnings.warn(

stdout: 2023-05-10 21:28:32.484
stdout: advance model exists:  False
 INFO : init end
model path: C:\Users\BenSa\Downloads\echo-v1.1.0.exe\echo\asr-server-v1.1.0\./model/vosk-model-en-us-0.22-lgraph

stderr:  INFO:ASR-API:init end

stdout: 2023-05-10 21:28:32.529  INFO : ASR API has been started
      Endpoint: POST http://127.0.0.1:8200/asr

asr server started
stderr:  INFO:ASR-API:ASR API has been started
  Endpoint: POST http://127.0.0.1:8200/asr

stderr: INFO:root:will run asr client

stderr: INFO:websockets.server:server listening on 0.0.0.0:8210

stderr: INFO:websockets.server:connection open

stderr: INFO:root:Connection from ('127.0.0.1', 60621)

stderr: INFO:root:Config {'sample_rate': 16000}

**Comment by rerender2021** [comment]
- 在播放视频的时候，立体声混音下面的麦克风条有跳动吗，需要确认设置是否有效
- 复制的文本是所有内容吗，通常在播放视频的时候，还会有识别到的语音文本输出，这里没有，说明没有语音识别成功
- “ C:\Users\BenSa\Downloads\**echo-v1.1.0.exe**\echo” 这个目录看起来有点奇怪，文件夹有.exe结尾的

**Comment by BenPong** [comment]
1. 输入立体声下面的麦克风条没有跳动（如附件的图）
2. 复制的文本已经是全部的文本了
3. 软件的目录地址是下载echo只有解压的路劲，只是测试好这个软件之后就会放到D盘的program文件夹去的，这个路径只是方面临时测试而已


如果视频的音频没有到输入立体声去的，那该怎么办呢？非常感谢
















在 2023-05-12 09:11:01，"rerender2021" ***@***.***> 写道：

在播放视频的时候，立体声混音下面的麦克风条有跳动吗，需要确认设置是否有效
复制的文本是所有内容吗，通常在播放视频的时候，还会有识别到的语音文本输出，这里没有，说明没有语音识别成功
“ C:\Users\BenSa\Downloads*echo-v1.1.0.exe*\echo” 这个目录看起来有点奇怪，文件夹有.exe结尾的

**Comment by rerender2021** [comment]
- “如附件的图”：我这边看不到附件的图
![image](https://github.com/rerender2021/echo/assets/87927336/c330cde2-d1a6-47e0-9624-4e61634549c7)

- "视频的音频没有到输入立体声"

你的声卡有什么特殊之处吗？只是普通电脑，还是说有专门配备过声卡相关设备。这里有一例独立声卡立体声混音可选择但无效对的：https://github.com/rerender2021/language-shadow/issues/4#issuecomment-1465088225

是否使用的是耳机，这里有一例使用耳机立体声混音无效的：https://github.com/rerender2021/echo/issues/4#issuecomment-1514032641

另外这有一例立体声混音也无效的：https://github.com/rerender2021/echo/issues/4#issuecomment-1487915675

解决方式：由于我没有遇到过，所以也只能通过搜索来看：

- 直接解决：比如知乎/搜索引擎上搜：https://www.zhihu.com/question/369514312 这里提到驱动版本可能有关
- 绕过这个问题：安装虚拟声卡，比如这里的用户后来改用voicemeeter成功的，如果你无法成功，另外也可搜教程换其它虚拟声卡 https://www.443w.com/tts/?post=59

**Comment by BenPong** [comment]
1. 哦，可能你在注册github的邮箱上看的话会看到附件的图片

2. 我的是外置声卡，能输入midi乐器，但没有话筒的输入。所以在win11的设置中，在输入哪里没法算立体声混音，但是我在youtube找能使得板载的声卡有立体声混音了方法，1. CMD->gpupdate，2.官网下载Realtek进行安装。这样的确在设置的声音输入里有了立体声混音。但是如你所见，电脑的声音就是没有到输入的地方去
3. voicemeeter我用过，win11设置-声音-输入里已经成功显示了voicemeeter，但是结果echo还是没有成功显示字幕。


我看你网站的说明win10设置立体声输入，使用的就是Realtek啊？我安装的也是这个板载声卡驱动，但为什么就是不行？
还有voicemeeter安装之后，虽然win11设置-声音-输入里已经成功显示了voicemeeter，是不是还要设置些什么啊？













在 2023-05-13 07:12:53，"rerender2021" ***@***.***> 写道：

“如附件的图”：我这边看不到附件的图


"视频的音频没有到输入立体声"

你的声卡有什么特殊之处吗？只是普通电脑，还是说有专门配备过声卡相关设备。这里有一例独立声卡立体声混音可选择但无效对的：rerender2021/language-shadow#4 (comment)

是否使用的是耳机，这里有一例使用耳机立体声混音无效的：#4 (comment)

另外这有一例立体声混音也无效的：#4 (comment)

解决方式：由于我没有遇到过，所以也只能通过搜索来看：

直接解决：比如知乎/搜索引擎上搜：https://www.zhihu.com/question/369514312 这里提到驱动版本可能有关
绕过这个问题：安装虚拟声卡，比如这里的用户后来改用
成功的，如果你无法成功，另外也可搜教程换其它虚拟声卡 https://www.443w.com/tts/?post=59

**Comment by rerender2021** [comment]
2. 这种设备问题比较复杂了，我没有这方面的经验，比如我没有外置声卡，不知道是不是用自带的声卡的时候需要先怎么关掉它? 会不会有影响。这种只能根据自己的情况搜索解决了：比如这里似乎和使用耳机/接口也有关系：https://answers.microsoft.com/zh-hans/windows/forum/all/win11%E6%97%A0%E6%B3%95%E5%9C%A8%E4%BD%BF%E7%94%A8/9c48a68b-cb25-4711-b6bb-7ee617e59c70

3. voicemeeter可以问问链接里那位成功使用的交流一下：[https://github.com/rerender2021/language-shadow/issues/4#issuecomment-1465088225](https://github.com/rerender2021/language-shadow/issues/4#issuecomment-1465088225)  或者试试其它虚拟声卡
