### ISSUE TITLE
运行失败了， asr 服务器

### ISSUE THREAD

**Issue by fffandpiao** [rerender2021/echo#5]
好像是编译失败，我不太明白，没学过 py 

这该怎么解决呢

这是输出信息：
```
parse config succeed, use it
parse config succeed, use it
try to init vosk asr engine
asrDir exists, start asr server D:\temp\asr-server
try to init nlp engine
nlp server not exist
stdout: 2023-03-22 11:31:48.453  INFO : ASR API is starting, please wait...

stdout:
You can find the C code in this temporary file: C:\Users\a\AppData\Local\Temp\theano_compilation_error_i2599uuz

stdout: 2023-03-22 11:31:49.255 ERROR :
stdout: Compilation failed (return status=1): C:\Users\a\AppData\Local\Theano\compiledir_Windows-10-10.0.18362-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.10-64\lazylinker_ext\mod.cpp:1:10: fatal error: Python.h: No such fi.  or directory.  #include <Python.h>.           ^~~~~~~~~~. compilation terminated.
    Traceback (most recent call last):
      File "theano\gof\lazylinker_c.py", line 76, in <module>
        raise ImportError(
    ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "theano\gof\lazylinker_c.py", line 99, in <module>
        raise ImportError(
    ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "main.py", line 38, in <module>
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
      File "punctuator\__init__.py", line 4, in <module>
        from .punc import Punctuator
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
      File "punctuator\punc.py", line 12, in <module>
        import theano
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
      File "theano\__init__.py", line 110, in <module>
        from theano.compile import (
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
      File "theano\compile\__init__.py", line 12, in <module>
stdout:
        from theano.compile.mode import *
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
      File "theano\compile\mode.py", line 11, in <module>
        import theano.gof.vm
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
      File "theano\gof\vm.py", line 674, in <module>
        from . import lazylinker_c
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
      File "theano\gof\lazylinker_c.py", line 139, in <module>
        cmodule.GCC_compiler.compile_str(dirname, code, location=loc,
      File "theano\gof\cmodule.py", line 2410, in compile_str
        raise Exception('Compilation failed (return status=%s): %s' %
    Exception: Compilation failed (return status=1): C:\Users\a\AppData\Local\Theano\compiledir_Windows-10-10.0.18362-SP0-Intel64_Family_6_Model_158_Stepping_10_GenuineIntel-3.8.10-64\lazylinker_ext\mod.cpp:1:10: fatal error: Python.h: No . ch file or directory.  #include <Python.h>.           ^~~~~~~~~~. compilation terminated.

asr server exit: 1
(node:19264) UnhandledPromiseRejectionWarning: false
(Use `echo --trace-warnings ...` to show where the warning was created)
(node:19264) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19264) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by fffandpiao** [comment]
哦哦，和4好像一样，说什么安装c++，我用 go 的时侯编译 sqlite 需要什么c++的玩意，好像安装过，我换台电脑试试看
