### ISSUE TITLE
GPU模式闪退报错

### ISSUE THREAD

**Issue by supermaruko** [rerender2021/echo#8]
GPU模式闪退报错如下
C:\[Develop]\echo-gpu>echo-use-gpu-debug.exe
parse config succeed, use it
parse config succeed, use it
try to init vosk asr engine
use asr-server-v1.1.0
asrDir exists, start asr server C:\[Develop]\echo-gpu\asr-server-v1.1.0
try to init nlp engine
nlp-gpu-server exists! use it
nlpDir exists, start nlp server C:\[Develop]\echo-gpu\nlp-gpu-server
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\[Develop]\echo-gpu\asr-server-v1.1.0\ASR-API.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:19)
    at onErrorNT (internal/child_process.js:472:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:12)
    at onErrorNT (internal/child_process.js:472:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\[Develop]\\echo-gpu\\asr-server-v1.1.0\\ASR-API.exe',
  path: 'C:\\[Develop]\\echo-gpu\\asr-server-v1.1.0\\ASR-API.exe',
  spawnargs: []
}

CUBA安装如下
C:\[Develop]\echo-gpu>nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_19:00:59_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0

**Comment by rerender2021** [comment]
直接错误原因是：
errno: -4058,
code: 'ENOENT',

![image](https://user-images.githubusercontent.com/87927336/229327352-27daeebd-aecb-4bcd-a1e4-1f0d1a484aed.png)



看上去是没成功启动语音识别服务器，可以看看路径下有没有C:\[Develop]\echo-gpu\asr-server-v1.1.0\ASR-API.exe
如果有的话，双击C:\[Develop]\echo-gpu\asr-server-v1.1.0\run.bat看看单独有什么报错没有

**Comment by rerender2021** [comment]
另外这个路径看起来和通常不一样：“C:[Develop]”

**Comment by supermaruko** [comment]
挪到根目录了 还是不行 /(ㄒoㄒ)/~~
C:\echo-gpu>echo-use-gpu-debug.exe
parse config succeed, use it
parse config succeed, use it
try to init vosk asr engine
use asr-server-v1.1.0
asrDir exists, start asr server C:\echo-gpu\asr-server-v1.1.0
try to init nlp engine
nlp-gpu-server exists! use it
nlpDir exists, start nlp server C:\echo-gpu\nlp-gpu-server
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\echo-gpu\asr-server-v1.1.0\ASR-API.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:19)
    at onErrorNT (internal/child_process.js:472:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:12)
    at onErrorNT (internal/child_process.js:472:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\echo-gpu\\asr-server-v1.1.0\\ASR-API.exe',
  path: 'C:\\echo-gpu\\asr-server-v1.1.0\\ASR-API.exe',
  spawnargs: []
}
